-- MySQL Script generated by MySQL Workbench
-- lun 01 nov 2021 11:59:32 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema portal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portal` ;

-- -----------------------------------------------------
-- Schema portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal` DEFAULT CHARACTER SET utf8 ;
USE `portal` ;



-- -----------------------------------------------------
-- Table `portal`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nick` VARCHAR(25) NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 122
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`palabras_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`palabras_email` (
  `idpalabras_email` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT(11) NOT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `palabras_detectar` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idpalabras_email`, `usuario_idUsuario`),
  INDEX `fk_palabras_email_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_palabras_email_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`secciones` (
  `idSecciones` TINYINT(20) NOT NULL AUTO_INCREMENT,
  `nombre_seccion` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idSecciones`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`tiempo_cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`tiempo_cambio` (
  `idTiempoCambio` INT(11) NOT NULL AUTO_INCREMENT,
  `tiempo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idTiempoCambio`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`post` (
  `idPost` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuarioPost` INT(11) NOT NULL,
  `secciones_idsecciones` TINYINT(20) NOT NULL,
  `tiempo_cambio_idTiempoCambio` INT(11) NOT NULL,
  `titulo` VARCHAR(60) NULL DEFAULT NULL,
  `comentario` VARCHAR(300) NULL DEFAULT NULL,
  `precio` VARCHAR(10) NULL DEFAULT NULL,
  `fechaPost` DATE NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_post_secciones1_idx` (`secciones_idsecciones` ASC),
  INDEX `fk_post_tiempo_cambio1_idx` (`tiempo_cambio_idTiempoCambio` ASC),
  CONSTRAINT `fk_post_secciones1`
    FOREIGN KEY (`secciones_idsecciones`)
    REFERENCES `portal`.`secciones` (`idSecciones`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tiempo_cambio1`
    FOREIGN KEY (`tiempo_cambio_idTiempoCambio`)
    REFERENCES `portal`.`tiempo_cambio` (`idTiempoCambio`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comentario_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`comentario_post` (
  `idComentariosPosts` INT NOT NULL AUTO_INCREMENT,
  `post_idPost` INT(11) NOT NULL,
  `idUsuarioComentario` INT(11) NULL,
  `nombreComenta` VARCHAR(20) CHARACTER SET 'utf8' NULL,
  `imgUsuarioComentario` VARCHAR(75) CHARACTER SET 'utf8' NULL,
  `tituloComentario` VARCHAR(75) CHARACTER SET 'utf8' NULL,
  `comentarioPost` VARCHAR(255) CHARACTER SET 'utf8' NULL,
  `ciudadComentario` VARCHAR(25) CHARACTER SET 'ucs2' NULL,
  `fechaComentario` DATE NULL,
  PRIMARY KEY (`idComentariosPosts`),
  INDEX `fk_ComentariosPosts_post_idx` (`post_idPost` ASC),
  CONSTRAINT `fk_ComentariosPosts_post`
    FOREIGN KEY (`post_idPost`)
    REFERENCES `portal`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Errores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`Errores` (
  `idErrores` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `codigo` INT NOT NULL,
  `usuario` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `fechaError` DATETIME NOT NULL,
  `mensaje` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `fichero` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `linea` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `trace` TEXT(750) CHARACTER SET 'utf8' NULL,
  `DatosIntroducidos` TEXT(1500) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idErrores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_expulsados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`usuarios_expulsados` (
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`),
  CONSTRAINT `fk_usuarios_expulsados_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `portal` ;

-- -----------------------------------------------------
-- Table `portal`.`busquedas_pbs_buscadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`busquedas_pbs_buscadas` (
  `idPbsBuscada` INT(11) NOT NULL AUTO_INCREMENT,
  `idPost_queridas` INT(11) NOT NULL,
  `palabrasBuscadas` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idPbsBuscada`),
  FULLTEXT INDEX `palabrasBuscadas` (`palabrasBuscadas` ASC),
  INDEX `fk_busquedas_pbs_buscadas_post1_idx` (`idPost_queridas` ASC),
  CONSTRAINT `fk_busquedas_pbs_buscadas_post1`
    FOREIGN KEY (`idPost_queridas`)
    REFERENCES `portal`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`busquedas_pbs_ofrecidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`busquedas_pbs_ofrecidas` (
  `idPbsOfrecida` INT(11) NOT NULL AUTO_INCREMENT,
  `idPost_ofrecidas` INT(11) NOT NULL,
  `palabrasOfrecidas` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idPbsOfrecida`),
  FULLTEXT INDEX `palabrasOfrecidas` (`palabrasOfrecidas` ASC),
  INDEX `fk_busquedas_pbs_ofrecidas_post1_idx` (`idPost_ofrecidas` ASC),
  CONSTRAINT `fk_busquedas_pbs_ofrecidas_post1`
    FOREIGN KEY (`idPost_ofrecidas`)
    REFERENCES `portal`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`datos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`datos_usuario` (
  `idDatosUsuario` INT(11) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido_1` VARCHAR(25) NULL DEFAULT NULL,
  `apellido_2` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` CHAR(9) NULL DEFAULT NULL,
  `genero` VARCHAR(8) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idDatosUsuario`),
  INDEX `fk_datos_usuario_usuario1_idx` (`idDatosUsuario` ASC),
  CONSTRAINT `fk_datos_usuario_usuario1`
    FOREIGN KEY (`idDatosUsuario`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`direccion` (
  `idDireccion` INT(11) NOT NULL,
  `calle` VARCHAR(25) NULL DEFAULT NULL,
  `numeroPortal` VARCHAR(10) NULL DEFAULT NULL,
  `ptr` VARCHAR(10) NULL DEFAULT NULL,
  `codigoPostal` CHAR(5) NULL DEFAULT NULL,
  `ciudad` VARCHAR(25) NOT NULL,
  `provincia` VARCHAR(30) CHARACTER SET 'utf8' NULL,
  `pais` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_direccion_usuario1_idx` (`idDireccion` ASC),
  CONSTRAINT `fk_direccion_usuario1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`genero` (
  `idGenero` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`imagenes` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `nickUsuario` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `post_idPost` INT(11) NOT NULL,
  `ruta` VARCHAR(55) CHARACTER SET 'utf8' NOT NULL,
  `texto` VARCHAR(70) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idImagen`, `nickUsuario`),
  INDEX `fk_imagenes_post1_idx` (`post_idPost` ASC),
  CONSTRAINT `fk_imagenes_post1`
    FOREIGN KEY (`post_idPost`)
    REFERENCES `portal`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`post_denunciados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`post_denunciados` (
  `idPostDenunciado` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPostDenunciado`, `usuario_idUsuario`),
  INDEX `fk_post_denunciados_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_post_denunciados_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`provincias` (
  `idProvincias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`idProvincias`))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`subsecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`subsecciones` (
  `idsubsecciones` INT(11) NOT NULL AUTO_INCREMENT,
  `secciones_idSecciones` TINYINT(20) NOT NULL,
  `nombreSubseccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubsecciones`, `secciones_idSecciones`),
  INDEX `fk_subsecciones_secciones1_idx` (`secciones_idSecciones` ASC),
  CONSTRAINT `fk_subsecciones_secciones1`
    FOREIGN KEY (`secciones_idSecciones`)
    REFERENCES `portal`.`secciones` (`idSecciones`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`usariosmensajespornoactivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`usariosmensajespornoactivos` (
  `idusariosMensajesPorNoActivos` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuarioNoActivo` INT(11) NOT NULL,
  `idUsuariosActivo` INT(11) NOT NULL,
  PRIMARY KEY (`idusariosMensajesPorNoActivos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `portal`.`usuarios_bloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal`.`usuarios_bloqueados` (
  `usuario_idUsuario` INT(11) NOT NULL,
  `idUsuarioBloqueado` INT(11) NOT NULL,
  `bloqueadoTotal` TINYINT(1) NOT NULL,
  `bloqueadoParcial` TINYINT(1) NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`, `idUsuarioBloqueado`),
  INDEX `fk_usuarios_bloqueados_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_usuarios_bloqueados_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `portal`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
